# Generated by Django 4.2 on 2026-07-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoConvenio',
            fields=[
                ('id_anexo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('tamanio_kb', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anexo_convenio',
                'managed': False,
            },
        ),
    ]
